### ISSUE TITLE
Issues with Say and it's Extent

### ISSUE THREAD

**Issue by Delubear** [gmriggs/EmoteScript#7] opened 2021-12-04 19:52 UTC
I believe searching the discord I saw a message saying, Say with an Extent of 1 should be full distance, but that hasn't been the case for me.  Standing not very far from my NPC and triggering an event with a Say would result in me not seeing the Say message.

However, after updating the extent to 40, I was then able to start seeing the Say messages.

The main issue I want to report is that I cannot find a way to set the Extent in the EmoteScript for the Say command.  Running the compile to SQL always results in an Invalid `type` of 0.

I've tried following the Delay syntax:
- Delay: 5, Say: test
which works for setting the Delay, but:
- Extent: 40, Say: test
results in an invalid result.

Is there not a way to set to the Extent for the Say command?  Is there another issue as to why the default Extent of 1 prevents me from seeing the message?

For example:

HearChat: !primary
    - Delay: 1, CastSpell: 1637 - Summon Primary Portal III
    - Say: Thank you. Here's a portal 

Compiles fine but sets the Extent of Say to 1, and when I test in-game, I get the CastSpell effect, but I do not see the Say

**Comment by gmriggs** [comment] 2021-12-05 15:26
investigating this one

i believe the Say emote / Extent feature for it was updated semi-recently in the past year, so I will have to review the updates that have been made to it

**Comment by gmriggs** [comment] 2021-12-05 16:04
It looks like the Say emote should have a default Extent of 0, instead of 1

Fixed in https://github.com/gmriggs/EmoteScript/pull/9

The updated default 0 extent for chat should now use the default local broadcast range (96 meters)

To answer your question about 'how do I set the extent for a chat emote', Extent would be something that fluent syntax doesn't support yet, and you would need to fallback on key/value syntax atm to specify an extent:

```
- Say: Message: Hello, Extent: 40
```

Hopefully the update will have the expected behavior by default with no extent specified

Thanks for reporting the issue!

**Closed as completed** 2021-12-09 01:40 UTC
